### ISSUE TITLE
chapter4 kprobe, "error: incomplete definition of type 'struct pt_regs'"

### ISSUE THREAD

**Issue by 0xmilkmix** [bpftools/linux-observability-with-bpf#15]
Hello,

I'm playing with the examples on Ubuntu 18.04 on their 5.0.0-37-generic kernel. Yet, running chapter4/kprobes/example.py, I get the following errors:

```
/virtual/main.c:5:62: error: incomplete definition of type 'struct pt_regs'
int do_sys_execve(struct pt_regs *ctx) { char* filename = ctx->di; char** argv = ctx->si; char** envp = ctx->dx;
                                                          ~~~^
/virtual/include/bcc/helpers.h:537:8: note: forward declaration of 'struct pt_regs'
struct pt_regs;
       ^
/virtual/main.c:5:85: error: incomplete definition of type 'struct pt_regs'
int do_sys_execve(struct pt_regs *ctx) { char* filename = ctx->di; char** argv = ctx->si; char** envp = ctx->dx;
                                                                                 ~~~^
/virtual/include/bcc/helpers.h:537:8: note: forward declaration of 'struct pt_regs'
struct pt_regs;
       ^
/virtual/main.c:5:108: error: incomplete definition of type 'struct pt_regs'
int do_sys_execve(struct pt_regs *ctx) { char* filename = ctx->di; char** argv = ctx->si; char** envp = ctx->dx;
                                                                                                        ~~~^
/virtual/include/bcc/helpers.h:537:8: note: forward declaration of 'struct pt_regs'
struct pt_regs;
       ^
3 errors generated.
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    bpf = BPF(text = bpf_source)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 301, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```

Any idea what might be going wrong? Also, running uprobes/example.py, nothing shows up on the output so maybe this is due to my host.

Best regards

note: I had to replace `void` by `char*` `char**`, otherwise, this error came:
```
/virtual/main.c:4:18: error: 'void' must be the first and only parameter if specified
int do_sys_execve(struct pt_regs *ctx, void filename, void argv, void envp) {
```

**Comment by fntlnz** [comment]
Thanks for fixing this @0xmilkmix !!! 
I also removed the other void arguments in the kprobe, they are not needed since we don't use them so can be dropped. 
Would you mind testing #17 ?

**Comment by fntlnz** [comment]
Ok now that #16 and #17 are merged I think we can close this!

@0xmilkmix thanks again!!
