### ISSUE TITLE
No such directory "/sys/kernel/debug/tracing/events/bpf" in vagrant fedora instance.

### ISSUE THREAD

**Issue by ryugwang** [bpftools/linux-observability-with-bpf#27]
Couldn't find `/sys/kernel/debug/tracing/events/bpf` directory mentioned in p.12 and p.52:
```
[root@bpfbook vagrant]# ls /sys/kernel/debug/tracing/events/bpf
ls: cannot access '/sys/kernel/debug/tracing/events/bpf': No such file or directory
```

and maybe because of this,  the tracepoint example(with `void ctx`  thing fixed) in p.52 failed.

```
[vagrant@bpfbook tracepoints]$ sudo python3 example.py
open(/sys/kernel/debug/tracing/events/bpf/bpf_prog_load/id): No such file or directory
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    bpf.attach_tracepoint(tp = "bpf:bpf_prog_load", fn_name = "trace_bpf_prog_load")
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 815, in attach_tracepoint
    (fn_name, tp))
Exception: Failed to attach BPF program b'trace_bpf_prog_load' to tracepoint b'bpf:bpf_prog_load'
```

FYI:
```
[root@bpfbook vagrant]# uname -a
Linux bpfbook 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[root@bpfbook vagrant]# find /sys/kernel/debug/tracing/events -type d | grep bpf
/sys/kernel/debug/tracing/events/syscalls/sys_enter_bpf
/sys/kernel/debug/tracing/events/syscalls/sys_exit_bpf

[root@bpfbook vagrant]# mount | grep kernel
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime,seclabel)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime,seclabel)
```

**Comment by s-seven** [comment]
I met the same problem. Have you solved it now?

**Comment by stevenlee87** [comment]
I met the same problem. Have you solved it now?

**Comment by ryugwang** [comment]
Unfortunately not.
